### ISSUE TITLE
Make buttons admin/page editor same size

### ISSUE THREAD

**Issue by PimTT** [MPvHarmelen/Freevle#206]
![schermafbeelding 2013-10-22 om 20 41 09](https://f.cloud.github.com/assets/1565818/1384173/ea479704-3b49-11e3-8cd6-62852fadcf35.png)

**Comment by PimTT** [comment]
- buttons same size and well aligned
- Also the selector.

**Comment by FMJansen** [comment]
Selector wasn't fixed, try http://bavotasan.com/2011/style-select-box-using-only-css/
