### ISSUE TITLE
Fix long slug problem

### ISSUE THREAD

**Issue by PimTT** [MPvHarmelen/Freevle#208]
![schermafbeelding 2013-10-22 om 20 48 06](https://f.cloud.github.com/assets/1565818/1384247/8b234380-3b4a-11e3-9d86-274a28891bd5.png)

**Comment by MPvHarmelen** [comment]
Why is this a problem? The only place a slug is used is in the url, and who care for it being accurate but long?
To be honest, I think this is a 'long title problem', because one shouldn't want a title that long.

**Comment by FMJansen** [comment]
It's a design problem; When the slug exceeds a certain size, it pushes down the buttons. This is not a real big problem though, since it doesn't look extremely bad and indeed, one shouldn't make such a long title.

**Comment by MPvHarmelen** [comment]
Can't you limit the text field with a certain length? The database has a limited length for the title too, so these should match.

**Comment by FMJansen** [comment]
I can, what is that length?

**Comment by martijnarts** [comment]
> Why is this a problem? The only place a slug is used is in the url, and who care for it being accurate but long?

This is a problem. Would you want to link someone to http://www.cygnusgymnasium.nl/news/je-moeder-op-een-bakfiets-gaat-heelhard-en-nu-gaat-het-design-langzaam-stuk-wacht-maar-nu-gaat-het-pas-echt-goed-fout-je-weet-zelfwantalles-gaat-lekkaahr/? (Idk the actual URL structure) The correct answer is no. http://www.cygnusgymnasium.nl/news/je-moeder-op-een-bakfiets-gaat-heelhard/ would be much better.

Limit slug length!
