### ISSUE TITLE
Reduce magic.

### ISSUE THREAD

**Issue by MPvHarmelen** [MPvHarmelen/Freevle#234]

**Comment by martijnarts** [comment]
Welcome to the Vaguest Issue Title Ever Awards 2015!

**Comment by FMJansen** [comment]
Hahahaha, amazing. I think it is about reducing vague, ununderstandable
code, though, so it would fit nicely, right?

**Comment by martijnarts** [comment]
Well yeah but that's extremely unspecific still. That's not an issue, that's like a project goal, or a roadmap item.
