### ISSUE TITLE
Rebuild the entire system. It honestly sucks right now.

### ISSUE THREAD

**Issue by martijnarts** [MPvHarmelen/Freevle#79]
Redesign and rebuild the entire Freevle system from the ground up, limit customizability making the system clearer and more sense. Work in the relative freedom of a different framework than Django ([Flask](http://flask.pocoo.org/) provides such freedom, for example, combined with [SQLAlchemy](http://www.sqlalchemy.org/))
- [ ]

**Comment by FMJansen** [comment]
Uh, u sure?
