### ISSUE TITLE
TemplateDoesNotExist

### ISSUE THREAD

**Issue by stephenswat** [MPvHarmelen/Freevle#8]
I started a server willy-nilly,
but it seems quite silly.
I went to the address,
but it just gave me stress.

To my very own terror,
it gave me an error.
It read TemplateDoesNotExist,
and dumped the data in a list.

The admin page functions,
but without its conjunctions,
the rest of the website is useless.

It left me quite juiceless,
Now finish your priming,
so I can stop rhyming.

Serieus, ik krijg dit:
TemplateDoesNotExist at /
index.html
Request Method: GET
Request URL:    http://localhost:8000/
Django Version: 1.3.1
Exception Type: TemplateDoesNotExist
Exception Value:  
index.html
Exception Location: /usr/local/lib/python2.7/dist-packages/django/template/loader.py in select_template, line 203
Python Executable:  /usr/bin/python
Python Version: 2.7.2
Python Path:  
['/home/stephen/Django/freevle/freevle',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PIL',
 '/usr/lib/python2.7/dist-packages/gst-0.10',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client',
 '/usr/lib/python2.7/dist-packages/ubuntuone-client',
 '/usr/lib/python2.7/dist-packages/ubuntuone-control-panel',
 '/usr/lib/python2.7/dist-packages/ubuntuone-couch',
 '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol']
Server time:    Mon, 16 Apr 2012 22:04:12 +0200

op localhost:8000, localhost:8000/admin doet het prima. What do?

**Comment by MPvHarmelen** [comment]
Heb je personalsettings wel goed gedaan? Je moet daar je path naar freevle ff goed zetten, miss dat daar nog schoolr staat?

Martin
